### ISSUE TITLE
[Feature request]:   Save updated 'ytdlg.json' in the running app, without shut down

### ISSUE THREAD

**Issue by altadr** [ErrorFlynn/ytdlp-interface#105] opened 2023-09-29 11:36 UTC
A simple Button 'Save ytdlp-interface.json now" 

to save 'ytdlg.json' after changes in the 'Queue' 
(be it entering a new URL or closing the 'select videos' window or similar actions)   

could be very helpful.   

Or even (maybe in a later version)
automatically saving the new altered version of 'ytdlg.json' after every change. 
At least after changes in the 'Queue' (be it entering a new URL 
or closing the 'select videos' window or similar actions).

[Up to now it is only saved when correctly shutting down the app, 
but in case of a crash before shutting down all alterations are lost, 
an updated version of 'ytdlg.json' is not available, 
only the then obsolete version documenting the pre-starting status.]  

 
Background:
Resuming downloads after a crash of "ytdlp-interface" seems still to be a problem to me. 
Knowing now that there should be a list of "unfinished_queue_items" in "ytdlp-interface.json", 
I see near to never anything else than "[ ]" there, 
though knowing that many items have not yet been done. 

The reason is clearly my fault as user, I normally start the application and use it, 
until the crash occurs. 
A more intelligent, or at least dilligent, user will certainly start the app, 
put the download links in, 
and close the app quickly, before a crash occurs, 
what leads to a fresh "ytdlp-interface.json" with all the download links saved in.  

Thereafter restarting the app with the now saved URLs should work flawlessly ...

But not so me, 
because of limited internet access oportunities and time I am eager to begin 
downloding immediately after entering the first URLs, 
and not closing the app before downloads are completed. 

So the next crashing occurs for unknown reasons 
(maybe related to connection problems or performance limits 
of my notbook, the power supply, or whatever else ...) and 
aborts downloading the queue items. 

This regularly leads to the "[ ]" in "unfinished_queue_items", 
because the "ytdlp-interface.json" is still the original one 
with empty queue and has not been updated after entering the URLs.  

So deliberately interrupting the downloadig for closing the app 
and with this refreshing the "ytdlp-interface.json" is a must, 
if resuming unfinished downloads is wished.

This could probably be simplified by 
a new button 'Save ytdlp-interface.json now"

or even (maybe in a later version)
a small automatic routine hopefully easy to implement.

After any change in the 'Queue' 
(is it entering a new URL, or closing the 'Select videos' window or similar actions)
the 'ytdlg.json' could automatically be saved in the new updated version.

Probably best by renaming the former version in 'ytdlg-old.json', 
and to avoid problems with by the crashing corrupted files, 
additionally renaming the former 'ytdlg-old.json' version in 'ytdlg-old-old.json', 
what should lead to at least two fall back versions.    

(Of course the process has to begin with 
deleting the then existing 'ytdlg-old-old.json', 
thereafter renaming the existing 'ytdlg-old.json' in 'ytdlg-old-old.json',  
followed by renaming 'ytdlg.json' in 'ytdlg-old.json' 
and then saving the updated ytdlg.json') 

Yes, I like multiple backups, especially in safety mechanisms ...

**Comment by altadr** [comment] 2023-09-29 11:40
Possibly this could also solve #103 ...

**Comment by altadr** [comment] 2023-10-07 18:43
My impression is it could be important that 
all downloading activity is stopped before shutting down, 

shutting down during active downloads seems to 
make the app crash and prevent updating the 'ytdlp-interface.json'. 

So maybe even for updating the 'ytdlp-interface.json' stopping all downloads before is neccessary? 

So the button could possibly 
uppermost stop all active downloads 
then save updated  'ytdlp-interface.json' 
before automatically resuming the stopped downloads ...

**Comment by ErrorFlynn** [comment] 2023-10-10 11:19
I have added a button to the settings window that allows you to write the settings file (which saves the queue state as well).

>My impression is it could be important that
>all downloading activity is stopped before shutting down,
>
>shutting down during active downloads seems to
>make the app crash and prevent updating the 'ytdlp-interface.json'.

That shouldn't cause a crash, but if it does, then yes, you should to stop all downloads before closing the window.

>So the button could possibly
>uppermost stop all active downloads
>then save updated 'ytdlp-interface.json'
>before automatically resuming the stopped downloads ...

That's not necessary. I'm 100% sure the crash isn't caused by writing the file, it's something that happens before that, when you close the window (probably a threading issue).

**Closed by ErrorFlynn** 2023-10-10 11:19 UTC
