### ISSUE TITLE
yt-dlp.exe: error: You must provide at least one URL.

### ISSUE THREAD

**Issue by kristofejro** [ErrorFlynn/ytdlp-interface#22] opened 2022-11-21 09:04 UTC
Hello,

In ytdlp-interface 1.6.2 whatever I try to download I get:

```
Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

Usage: yt-dlp.exe [OPTIONS] URL [URL...]
yt-dlp.exe: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

[GUI] yt-dlp.exe process has exited
```

Example command line in output:

`[GUI] executing command line: "C:\UT\Apps\ytdlp-interface\yt-dlp.exe" -S "res:1080,vext:mp4,aext:m4a,fps" --windows-filenames --no-mtime  -P "D:\" -o %(title)s.%(ext)s https://www.youtube.com/watch?v=S1t_8iRFVs4`

Am I doing something wrong? In 1.5.1 it was working just fine.

**Comment by ErrorFlynn** [comment] 2022-11-22 01:29
I haven't tested, but from just looking at that command line, I think it's because you're using the root of the drive. Without going into technical details, the problem is that the path ends in backslash. If you instead use a subdirectory of `D` (for example, `D:\mydir`), it should work. I will do some testing and report back.

**Comment by ErrorFlynn** [comment] 2022-11-22 03:29
I've released a new version with a fix for this issue, please update.

**Closed by ErrorFlynn** 2022-11-22 03:29 UTC

**Comment by kristofejro** [comment] 2022-11-22 06:28
Thanks. It works much better now.
