### ISSUE TITLE
automatic close the app after 2 seconds

### ISSUE THREAD

**Issue by benshgit** [ErrorFlynn/ytdlp-interface#37] opened 2023-02-11 00:57 UTC
the latest v1.9, will close itself automaticlly after 2 seconds from openning it, in Windows 10 22H2.

**Comment by ErrorFlynn** [comment] 2023-02-11 14:09
That's strange, try deleting the settings file (`ytdlp-interface.json`).

**Comment by benshgit** [comment] 2023-02-12 04:21
Just now, the problem disappears. 
Yesterday, however, the problem occurred repeatedly although I deleted the config file. I don't know the reason. 
I'm trying to open the other applications that opened yesterday while opening the ydl-interface, and the problem no longer occurs. So, leave it alone, forget it, until it occurs again.

**Comment by benshgit** [comment] 2023-02-12 08:50
It's now 4:45pm, I'm trying to open the application. The problem occurs again and again. This time, I recorded the screen. So, I would like to send you the screen record video file if you give me your email address or other.

**Comment by ErrorFlynn** [comment] 2023-02-12 18:41
I don't think it's a good idea for me to post my email address in public, but you can upload the video to some video hosting site and post the link here if you want.

My suspicion is that the program crashes after checking GitHub for a new version (which it does at startup), because it gets an unexpected response. When it's crashing, cut the internet connection and see if it still crashes.

In the next version I plan to add exception handling (a mechanism that lets the program display an error and continue, instead of silently crashing) wherever it's appropriate in the code.

**Comment by DougPlayer** [comment] 2023-02-17 02:59
I have a similar issue - perhaps the same.  I've pinned ytdlp-interface.exe to my Win 10 taskbar.  It runs fine the first time, and creates ytdlp-interface.json with my preferences.  However, running it the second time, the Taskbar icon shows that the program is running, but no window appears.  If I hover over the taskbar icon, then right-click on the small window that pops up over the pinned icon, and select "Maximize", the window does appear, and the program functions correctly.  Also, if I delete the .json file after running the program, and then restart it, the program will run properly again.  It's as though the .json file is interfering with the proper display of the program window.

**Comment by ErrorFlynn** [comment] 2023-02-17 03:43
>However, running it the second time, the Taskbar icon shows that the program is running, but no window appears.

I was able to reproduce this by closing the program while minimized (is that what you did?), which caused the `x` and `y` coordinates to be `-32000` in the settings file, so the next time I started the program the window was offscreen. I'll probably release a patch version with a fix for this bug in a couple of days, thank you for letting me know about it.

>If I hover over the taskbar icon, then right-click on the small window that pops up over the pinned icon, and select "Maximize", the window does appear, and the program functions correctly.

A better workaround would be to click on the small window to give the program window the input focus, and then press `Ctrl+Num0` to reset its size and position to default values.

**Comment by DougPlayer** [comment] 2023-02-17 14:50
> I was able to reproduce this by closing the program while minimized (is that what you did?), which caused the `x` and `y` coordinates to be `-32000` in the settings file, so the next time I started the program the window was offscreen. I'll probably release a patch version with a fix for this bug in a couple of days, thank you for letting me know about it.

Yes - I closed the program while minimized.



> A better workaround would be to click on the small window to give the program window the input focus, and then press `Ctrl+Num0` to reset its size and position to default values.

Thanks !

**Comment by DougPlayer** [comment] 2023-02-27 21:31
The newest version 1.91 has resolved the issue I posted about above.  thx

**Closed** 2023-02-28 00:59 UTC
